ref: Make description in SpanProtocol nonnull
getsentry/sentry-cocoa pull request #1059
Opened 2021-04-20 15:07 UTC by philipphofmann

## :scroll: Description

SentrySpanProtocol.startChildWithOperation has an overload without a
description if you don't want to specify a description. We don't need
the description to be nullable.

## :bulb: Motivation and Context

Improves the API.

## :green_heart: How did you test it?
CI.

## :pencil: Checklist

- [x] I reviewed the submitted code
- [x] I added tests to verify the changes
- [ ] I updated the CHANGELOG if needed
- [x] I updated the docs if needed
- [x] Review from the native team if needed
- [ ] No breaking changes

## :crystal_ball: Next steps

2021-04-20 16:08 UTC, bruno-garcia requested changes
This was a conscious decision and we discussed it on the PR

The problem with this (and I hit this problem using the API) is that if you are calling this with a "string variable" for `description` which you don't know if it's null or not, you need to do a `If` check to call one overload or the other.

This code was done in .NET (the way you're proposing here) and it's just not a good API.

`description` is nullable, so makes sense and it's a better usability to have the overload be nullable

2021-04-21 07:47 UTC, philipphofmann commented
Wouldn't you agree that you don't see `nullable` in method overloads rarely? We usually don't do this in the SDK
```
SentrySDK.capture(event: , scope: )
SentrySDK.capture(event: , block: )
SentrySDK.capture(message: , scope: )
SentrySDK.capture(message: , block: )
// ...

Attachment(data: , filename: , contentType: )
```

I also don't see this often in standard libraries, so for me, it looks weird. I'm a huge fan of the [null safety](https://kotlinlang.org/docs/null-safety.html) for example in Kotlin and for me, it makes sense to use it rarely. In Swift per default, every value is `nonnull` as well and you have to declare it as optional if you want it to be null. Again it makes sense to me to use `nullable` judiciously. 

> The problem with this (and I hit this problem using the API in .NET) is that if you are calling this with a "string variable" for description which you don't know if it's null or not, you need to do a If check to call one overload or the other.

You would have this problem with every method overload where the parameters are `nonnull`. I think in this case you should make sure the description can't be null. It forces you to give it a value when you use the description. Therefore for me, it is actually a good API, because it avoids nullable values.

2021-04-21 08:20 UTC, marandaneto commented
> Wouldn't you agree that you don't see `nullable` in method overloads rarely? We usually don't do this in the SDK
> 
> ```
> SentrySDK.capture(event: , scope: )
> SentrySDK.capture(event: , block: )
> SentrySDK.capture(message: , scope: )
> SentrySDK.capture(message: , block: )
> // ...
> 
> Attachment(data: , filename: , contentType: )
> ```
> 
> I also don't see this often in standard libraries, so for me, it looks weird. I'm a huge fan of the [null safety](https://kotlinlang.org/docs/null-safety.html) for example in Kotlin and for me, it makes sense to use it rarely. In Swift per default, every value is `nonnull` as well and you have to declare it as optional if you want it to be null. Again it makes sense to me to use `nullable` judiciously.
> 
> > The problem with this (and I hit this problem using the API in .NET) is that if you are calling this with a "string variable" for description which you don't know if it's null or not, you need to do a If check to call one overload or the other.
> 
> You would have this problem with every method overload where the parameters are `nonnull`. I think in this case you should make sure the description can't be null. It forces you to give it a value when you use the description. Therefore for me, it is actually a good API, because it avoids nullable values.

obviously, this is a trade-off, both use cases here have pros/cons, what makes me decide if a nullable field should have a non-nullable field in the method param is if this could be used at runtime dynamically, eg description is likely being used with a SQL query or literally anything else, including a request or response value, which could be null/empty or not, so it's just easier to allow them doing do(x, y) instead of if (x & y) call do(x, y) instead do(x).

2021-04-21 13:27 UTC, closed without merging

2021-04-21 13:56 UTC, brustolin commented
I'm late to the discussion but I agree that if the property can be null, its value in any method should allow null.